# Generated by Django 4.2.8 on 2024-01-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="published_at",
            field=models.BooleanField(default=True),
        ),
    ]
