# Generated by Django 4.2.8 on 2024-01-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0002_post_published_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="email",
            field=models.EmailField(default="test@gamail.com", max_length=254),
            preserve_default=False,
        ),
    ]
