# Generated by Django 4.2.8 on 2024-01-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0006_post_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.CharField(
                choices=[("WB", "Web Development"), ("DS", "Data Science")],
                max_length=20,
            ),
        ),
    ]
